import javax.imageio.ImageIO
import javax.xml.parsers.DocumentBuilderFactory

plugins {
    alias(libs.plugins.kotlin.multiplatform)
}

kotlin {
    jvmToolchain(21)
    jvm()
    js(IR) {
        browser()
        binaries.library()
    }

    sourceSets {
        commonMain {
            dependencies {
                api(project(":s52-core"))
                api(project(":s52-preslib"))
                api(project(":s52-csp"))
            }
        }
        jvmTest {
            dependencies {
                implementation(kotlin("test"))
            }
        }
    }
}

tasks.register<JavaExec>("exportOpenCpnSymbologyImages") {
    group = "documentation"
    description = "Generates per-asset SVG images from a real imported OpenCPN chartsymbols.xml payload."
    val jvmJarTask = tasks.named<org.gradle.jvm.tasks.Jar>("jvmJar")
    dependsOn(jvmJarTask)
    mainClass.set("io.github.s52.api.tools.S52SymbologyImageExportMainKt")
    classpath(
        files(jvmJarTask.flatMap { it.archiveFile }),
        configurations.named("jvmRuntimeClasspath")
    )

    doFirst {
        val outputDir = rootProject.layout.buildDirectory.dir("s52-symbology-images").get().asFile.absolutePath
        val bundledPlib = rootProject.layout.projectDirectory.file("s52/opencpn/chartsymbols.xml").asFile
        val plibFile = providers.gradleProperty("opencpn.chartsymbols")
            .orElse(providers.environmentVariable("OPENCPN_CHARTSYMBOLS_XML_FILE"))
            .orNull
            ?.let(::file)
            ?: bundledPlib.takeIf { it.isFile }
            ?: error("Missing real OpenCPN chartsymbols.xml payload. Set -Popencpn.chartsymbols=/path/to/chartsymbols.xml, OPENCPN_CHARTSYMBOLS_XML_FILE, or commit s52/opencpn/chartsymbols.xml.")

        validateOpenCpnInputsForCleanCheckout(plibFile)
        args(outputDir, plibFile.absolutePath)
    }
}

fun validateOpenCpnInputsForCleanCheckout(chartsymbolsXml: java.io.File) {
    check(chartsymbolsXml.isFile) { "Missing OpenCPN chartsymbols.xml: ${chartsymbolsXml.absolutePath}" }
    check(chartsymbolsXml.length() > 1024L) { "OpenCPN chartsymbols.xml is unexpectedly small: ${chartsymbolsXml.absolutePath}" }

    val xmlFactory = DocumentBuilderFactory.newInstance().apply {
        isNamespaceAware = false
        isExpandEntityReferences = false
        setFeature("http://apache.org/xml/features/disallow-doctype-decl", true)
        setFeature("http://xml.org/sax/features/external-general-entities", false)
        setFeature("http://xml.org/sax/features/external-parameter-entities", false)
        setFeature("http://apache.org/xml/features/nonvalidating/load-external-dtd", false)
    }
    val document = xmlFactory.newDocumentBuilder().parse(chartsymbolsXml)
    val symbolCount = document.getElementsByTagName("symbol").length
    val lineStyleCount = document.getElementsByTagName("line-style").length + document.getElementsByTagName("line_style").length
    val patternCount = document.getElementsByTagName("pattern").length
    check(symbolCount >= 50) { "OpenCPN chartsymbols.xml has too few symbols ($symbolCount): ${chartsymbolsXml.absolutePath}" }
    check(lineStyleCount > 0) { "OpenCPN chartsymbols.xml has no line styles: ${chartsymbolsXml.absolutePath}" }
    check(patternCount > 0) { "OpenCPN chartsymbols.xml has no patterns: ${chartsymbolsXml.absolutePath}" }

    val projectDir = rootProject.layout.projectDirectory.asFile
    listOf("day", "dusk", "dark").forEach { palette ->
        val png = projectDir.resolve("s52/opencpn/rastersymbols-$palette.png")
        check(png.isFile) { "Missing bundled OpenCPN raster symbol atlas: ${png.path}" }
        check(png.length() > 1024L) { "Bundled OpenCPN raster symbol atlas is unexpectedly small: ${png.path}" }
        val image = ImageIO.read(png)
        check(image != null && image.width > 0 && image.height > 0) { "Invalid PNG raster symbol atlas: ${png.path}" }
    }

    val yarnLock = projectDir.resolve("kotlin-js-store/yarn.lock")
    check(yarnLock.isFile) { "Missing committed Kotlin/JS yarn lock: ${yarnLock.path}" }
    val lockText = yarnLock.readText()
    check("# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY." in lockText) {
        "kotlin-js-store/yarn.lock does not look like the generated Yarn v1 lock file"
    }
}
