#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

require_file() {
  local path="$1"
  if [[ ! -s "$path" ]]; then
    echo "Missing or empty required Phase 22 file: $path" >&2
    exit 1
  fi
}

require_file "s52/opencpn/chartsymbols.xml"
require_file "s52/opencpn/rastersymbols-day.png"
require_file "s52/opencpn/rastersymbols-dusk.png"
require_file "s52/opencpn/rastersymbols-dark.png"
require_file "kotlin-js-store/yarn.lock"

python3 - <<'PY'
from pathlib import Path
import struct
import xml.etree.ElementTree as ET

root = Path('.')
xml_path = root / 's52/opencpn/chartsymbols.xml'
try:
    tree = ET.parse(xml_path)
except ET.ParseError as exc:
    raise SystemExit(f'Invalid OpenCPN chartsymbols.xml: {exc}')

xml_root = tree.getroot()
symbol_count = len(xml_root.findall('.//symbol'))
pattern_count = len(xml_root.findall('.//pattern'))
line_style_count = len(xml_root.findall('.//line-style')) + len(xml_root.findall('.//line_style'))
if symbol_count < 50:
    raise SystemExit(f'OpenCPN chartsymbols.xml has too few symbols: {symbol_count}')
if pattern_count <= 0:
    raise SystemExit('OpenCPN chartsymbols.xml has no patterns')
if line_style_count <= 0:
    raise SystemExit('OpenCPN chartsymbols.xml has no line styles')

for name in ('day', 'dusk', 'dark'):
    path = root / f's52/opencpn/rastersymbols-{name}.png'
    data = path.read_bytes()
    if len(data) < 33 or not data.startswith(b'\x89PNG\r\n\x1a\n'):
        raise SystemExit(f'{path} is not a valid PNG file')
    width, height = struct.unpack('>II', data[16:24])
    if width <= 0 or height <= 0:
        raise SystemExit(f'{path} has invalid dimensions: {width}x{height}')

lock = (root / 'kotlin-js-store/yarn.lock').read_text(encoding='utf-8', errors='replace')
if '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.' not in lock:
    raise SystemExit('kotlin-js-store/yarn.lock does not look like the committed Kotlin/Yarn v1 lock file')
PY

lock_hash() {
  python3 - <<'PY'
from pathlib import Path
import hashlib
print(hashlib.sha256(Path('kotlin-js-store/yarn.lock').read_bytes()).hexdigest())
PY
}

LOCK_BEFORE="$(lock_hash)"

gradle --no-daemon phase22Check "$@"

LOCK_AFTER="$(lock_hash)"
if [[ "$LOCK_BEFORE" != "$LOCK_AFTER" ]]; then
  echo "kotlin-js-store/yarn.lock changed during phase22Check." >&2
  echo "Before: $LOCK_BEFORE" >&2
  echo "After:  $LOCK_AFTER" >&2
  echo "Regenerate and commit the Kotlin/JS lock state, then rerun scripts/phase22-clean-check.sh." >&2
  exit 1
fi

echo "Phase 22 clean-check guard passed: bundled OpenCPN inputs are valid and yarn.lock was unchanged."
