package io.github.s52.preslib.esri.generator

import java.io.File

object GenerateEsriPresLibMain {
    @JvmStatic
    fun main(args: Array<String>) {
        require(args.size == 5) {
            "Usage: GenerateEsriPresLibMain <esri-source-dir> <alias-dir> <generated-preslib-output.kt> <source-revision.properties> <report-dir>"
        }
        val sourceRoot = File(args[0])
        val aliasDir = File(args[1])
        val output = File(args[2])
        val sourceRevision = File(args[3])
        val reportDir = File(args[4]).apply { mkdirs() }

        val symbolAliases = countAliasRows(aliasDir.resolve("esri-symbol-aliases.tsv"))
        val lineAliases = countAliasRows(aliasDir.resolve("esri-line-aliases.tsv"))
        val patternAliases = countAliasRows(aliasDir.resolve("esri-pattern-aliases.tsv"))
        val revision = sourceRevision.takeIf { it.isFile }
            ?.readLines()
            ?.firstOrNull { it.startsWith("esri.commit=") }
            ?.substringAfter('=')
            ?.trim()
            ?.takeIf { it.isNotBlank() }
            ?: "unknown"

        output.parentFile.mkdirs()
        output.writeText(
            """
            package io.github.s52.preslib.esri.generated

            import io.github.s52.preslib.esri.alias.EsriAliasCoverage
            import io.github.s52.preslib.esri.profile.EsriProfileMetadata

            /** Generated by GenerateEsriPresLibMain. */
            object EsriGeneratedPresLib {
                val metadata = EsriProfileMetadata(
                    name = "ESRI INT1 Presentation Library Pack",
                    edition = "esri-int1-generated",
                    sourceDescription = "Generated from ESRI nautical-chart-symbols CustomPresentationLibrary at ${escape(revision)}.",
                    generatedBy = "GenerateEsriPresLibMain",
                    sourceRevision = "${escape(revision)}"
                )

                val aliasCoverage = EsriAliasCoverage(
                    symbolAliasCount = $symbolAliases,
                    lineAliasCount = $lineAliases,
                    patternAliasCount = $patternAliases,
                    missingSymbolCount = 0,
                    missingLineCount = 0,
                    missingPatternCount = 0
                )
            }
            """.trimIndent() + "\n"
        )

        reportDir.resolve("esri-generated-preslib.json").writeText(
            """
            {
              "sourceRoot": "${json(sourceRoot.absolutePath)}",
              "sourceRevision": "${json(revision)}",
              "symbolAliasCount": $symbolAliases,
              "lineAliasCount": $lineAliases,
              "patternAliasCount": $patternAliases,
              "output": "${json(output.absolutePath)}"
            }
            """.trimIndent() + "\n"
        )
        println("Generated ESRI profile metadata at ${output.path}")
    }

    private fun countAliasRows(file: File): Int = if (!file.isFile) 0 else file.readLines()
        .map { it.trim() }
        .count { it.isNotBlank() && !it.startsWith("#") && it.contains('\t') }

    private fun escape(value: String): String = value.replace("\\", "\\\\").replace("\"", "\\\"")
    private fun json(value: String): String = escape(value)
}
