package io.github.s52.api

/**
 * Phase 19 portable text artifact produced by the public facade.
 *
 * Artifacts are intentionally dependency-free and text-only so they can be
 * attached to GitHub issues, uploaded as CI artifacts, written by browser
 * demos, or embedded in downstream validation reports without requiring a zip
 * or JSON library in commonMain.
 */
data class S52Artifact(
    val path: String,
    val mediaType: String,
    val text: String
) {
    init {
        require(path.isNotBlank()) { "Artifact path must not be blank." }
        require(!path.startsWith("/")) { "Artifact path must be relative: $path" }
        require(".." !in path.split('/')) { "Artifact path must not contain '..': $path" }
        require(mediaType.isNotBlank()) { "Artifact media type must not be blank." }
    }

    val lineCount: Int get() = if (text.isBlank()) 0 else text.lines().size
    val charCount: Int get() = text.length

    fun preview(maxLines: Int = DEFAULT_PREVIEW_LINES): String {
        require(maxLines >= 0) { "maxLines must be non-negative." }
        if (maxLines == 0 || text.isBlank()) return ""
        val lines = text.lines()
        val limited = lines.take(maxLines)
        val omitted = lines.size - limited.size
        return buildString {
            limited.forEach { appendLine(it) }
            if (omitted > 0) appendLine("... $omitted more line(s) omitted ...")
        }.trimEnd()
    }

    companion object {
        const val DEFAULT_PREVIEW_LINES: Int = 20
    }
}

/** Collection of named Phase 19 artifacts with stable index formats. */
data class S52ArtifactBundle(
    val name: String,
    val artifacts: List<S52Artifact>
) {
    init {
        require(name.isNotBlank()) { "Artifact bundle name must not be blank." }
        val duplicatePaths = artifacts.groupingBy { it.path }.eachCount().filterValues { it > 1 }.keys
        require(duplicatePaths.isEmpty()) { "Duplicate artifact paths: $duplicatePaths" }
    }

    val artifactCount: Int get() = artifacts.size
    val totalCharacters: Int get() = artifacts.sumOf { it.charCount }
    val hasErrors: Boolean get() = find("diagnostics.properties")?.text?.lines()?.any { it == "hasErrors=true" } ?: false

    fun find(path: String): S52Artifact? = artifacts.firstOrNull { it.path == path }

    fun require(path: String): S52Artifact = find(path)
        ?: error("Artifact '$path' not found. Available artifacts: ${artifacts.joinToString { it.path }}")

    fun toMarkdownIndex(): String = buildString {
        appendLine("# S-52 Artifact Bundle")
        appendLine()
        appendLine("- Name: $name")
        appendLine("- Artifacts: $artifactCount")
        appendLine("- Total characters: $totalCharacters")
        appendLine("- Has errors: $hasErrors")
        appendLine()
        appendLine("## Files")
        appendLine()
        artifacts.sortedBy { it.path }.forEach { artifact ->
            appendLine("- `${artifact.path}` — ${artifact.mediaType}, ${artifact.lineCount} line(s), ${artifact.charCount} char(s)")
        }
    }

    fun toPropertiesIndex(): String = buildString {
        appendLine("name=$name")
        appendLine("artifactCount=$artifactCount")
        appendLine("totalCharacters=$totalCharacters")
        appendLine("hasErrors=$hasErrors")
        artifacts.sortedBy { it.path }.forEachIndexed { index, artifact ->
            appendLine("artifact.$index.path=${artifact.path}")
            appendLine("artifact.$index.mediaType=${artifact.mediaType}")
            appendLine("artifact.$index.lineCount=${artifact.lineCount}")
            appendLine("artifact.$index.charCount=${artifact.charCount}")
        }
    }
}

/** Controls which text artifacts are generated by [S52ArtifactExporter]. */
data class S52ArtifactExportOptions(
    val includeManifestMarkdown: Boolean = true,
    val includeDiagnosticsMarkdown: Boolean = true,
    val includeDiagnosticsProperties: Boolean = true,
    val includeProfileMarkdown: Boolean = true,
    val includeProfileProperties: Boolean = true,
    val includeStaticCompletenessMarkdown: Boolean = true,
    val includeCommandValidationMarkdown: Boolean = true,
    val includeFullTranscript: Boolean = true,
    val includeTranscriptPreview: Boolean = true,
    val transcriptPreviewLineLimit: Int = S52DiagnosticBundle.DEFAULT_TRANSCRIPT_PREVIEW_LINES
) {
    init {
        require(transcriptPreviewLineLimit >= 0) { "transcriptPreviewLineLimit must be non-negative." }
    }

    companion object {
        val default: S52ArtifactExportOptions = S52ArtifactExportOptions()

        val compact: S52ArtifactExportOptions = S52ArtifactExportOptions(
            includeStaticCompletenessMarkdown = false,
            includeCommandValidationMarkdown = false,
            includeFullTranscript = false,
            transcriptPreviewLineLimit = 10
        )
    }
}

/**
 * Dependency-free exporter that packages portrayal result text into stable file
 * names. It does not write files itself; downstream apps decide where to store
 * or upload the artifacts.
 */
object S52ArtifactExporter {
    const val MEDIA_MARKDOWN: String = "text/markdown"
    const val MEDIA_PROPERTIES: String = "text/plain; format=properties"
    const val MEDIA_JSONL: String = "application/jsonl"
    const val MEDIA_TEXT: String = "text/plain"

    fun export(
        session: S52PortrayalSession,
        request: S52PortrayalRequest,
        name: String = "s52-kotlin-webgl-artifacts",
        profile: S52PortrayalProfile? = null,
        options: S52ArtifactExportOptions = S52ArtifactExportOptions.default
    ): S52ArtifactBundle {
        val result = session.portray(request)
        val manifest = session.manifest(name)
        val diagnostics = S52Diagnostics.fromResult(
            manifest = manifest,
            request = request,
            result = result,
            transcriptPreviewLineLimit = options.transcriptPreviewLineLimit
        )
        val artifacts = mutableListOf<S52Artifact>()

        artifacts += S52Artifact("index.md", MEDIA_MARKDOWN, buildIndexMarkdown(name, profile, diagnostics))

        if (options.includeManifestMarkdown) {
            artifacts += S52Artifact("manifest.md", MEDIA_MARKDOWN, manifest.toMarkdown())
        }
        if (options.includeDiagnosticsMarkdown) {
            artifacts += S52Artifact("diagnostics.md", MEDIA_MARKDOWN, diagnostics.toMarkdown())
        }
        if (options.includeDiagnosticsProperties) {
            artifacts += S52Artifact("diagnostics.properties", MEDIA_PROPERTIES, diagnostics.toProperties())
        } else {
            artifacts += S52Artifact("diagnostics.properties", MEDIA_PROPERTIES, "hasErrors=${diagnostics.hasErrors}\n")
        }
        if (profile != null && options.includeProfileMarkdown) {
            artifacts += S52Artifact("profile.md", MEDIA_MARKDOWN, profile.summary().toMarkdown())
        }
        if (profile != null && options.includeProfileProperties) {
            artifacts += S52Artifact("profile.properties", MEDIA_PROPERTIES, profile.toProperties())
        }
        if (options.includeStaticCompletenessMarkdown) {
            artifacts += S52Artifact("static-completeness.md", MEDIA_MARKDOWN, result.staticCompleteness.toMarkdown())
        }
        if (options.includeCommandValidationMarkdown) {
            artifacts += S52Artifact("command-validation.md", MEDIA_MARKDOWN, result.commandValidation.toMarkdown())
        }
        if (options.includeFullTranscript) {
            artifacts += S52Artifact("commands.jsonl", MEDIA_JSONL, result.transcript)
        }
        if (options.includeTranscriptPreview) {
            artifacts += S52Artifact("commands-preview.txt", MEDIA_TEXT, diagnostics.transcriptPreview())
        }

        val bundle = S52ArtifactBundle(name = name, artifacts = artifacts)
        return bundle.copy(
            artifacts = listOf(
                S52Artifact("bundle-index.md", MEDIA_MARKDOWN, bundle.toMarkdownIndex()),
                S52Artifact("bundle-index.properties", MEDIA_PROPERTIES, bundle.toPropertiesIndex())
            ) + artifacts
        )
    }

    private fun buildIndexMarkdown(
        name: String,
        profile: S52PortrayalProfile?,
        diagnostics: S52DiagnosticBundle
    ): String = buildString {
        appendLine("# S-52 Portrayal Artifact Export")
        appendLine()
        appendLine("- Name: $name")
        appendLine("- Safety status: ${diagnostics.manifest.safetyStatus}")
        appendLine("- Profile: ${profile?.id ?: "custom-request"}")
        appendLine("- Features: ${diagnostics.featureCount}")
        appendLine("- Commands: ${diagnostics.commandCount}")
        appendLine("- Has errors: ${diagnostics.hasErrors}")
        appendLine()
        appendLine("This artifact export is for testing, issue reports, and integration handoff only. It is not a navigation product and is not a type-approved ECDIS output.")
    }
}

fun S52PortrayalSession.artifactBundle(
    request: S52PortrayalRequest,
    name: String = "s52-kotlin-webgl-artifacts",
    options: S52ArtifactExportOptions = S52ArtifactExportOptions.default
): S52ArtifactBundle = S52ArtifactExporter.export(
    session = this,
    request = request,
    name = name,
    profile = null,
    options = options
)

fun S52PortrayalSession.artifactBundle(
    features: List<io.github.s52.core.model.EncFeature>,
    profile: S52PortrayalProfile = S52ProfileCatalog.default,
    name: String = "s52-kotlin-webgl-artifacts",
    options: S52ArtifactExportOptions = S52ArtifactExportOptions.default,
    context: io.github.s52.core.settings.PortrayalContext = profile.defaultContext()
): S52ArtifactBundle = S52ArtifactExporter.export(
    session = this,
    request = profile.request(features, context),
    name = name,
    profile = profile,
    options = options
)
