package io.github.s52.catalog

/**
 * Phase 1 typed S-57 attribute catalogue used by lookup matching and CSPs.
 *
 * The enum is data-only. It intentionally contains no portrayal logic.
 */
enum class S57Attribute(
    val acronym: String,
    val code: Int?,
    val valueKind: S57AttributeValueKind = S57AttributeValueKind.Unknown
) {
    AGENCY("AGENCY", null, S57AttributeValueKind.Enumeration),
    BCNSHP("BCNSHP", null, S57AttributeValueKind.Enumeration),
    BOYSHP("BOYSHP", null, S57AttributeValueKind.Enumeration),
    BURDEP("BURDEP", null, S57AttributeValueKind.Decimal),
    CALSGN("CALSGN", null, S57AttributeValueKind.Text),
    CATACH("CATACH", null, S57AttributeValueKind.Enumeration),
    CATBRG("CATBRG", null, S57AttributeValueKind.Enumeration),
    CATBUA("CATBUA", null, S57AttributeValueKind.Enumeration),
    CATCAM("CATCAM", null, S57AttributeValueKind.Enumeration),
    CATCAN("CATCAN", null, S57AttributeValueKind.Enumeration),
    CATCBL("CATCBL", null, S57AttributeValueKind.Enumeration),
    CATCHP("CATCHP", null, S57AttributeValueKind.Enumeration),
    CATCOA("CATCOA", null, S57AttributeValueKind.Enumeration),
    CATCON("CATCON", null, S57AttributeValueKind.Enumeration),
    CATCOV("CATCOV", null, S57AttributeValueKind.Enumeration),
    CATCRN("CATCRN", null, S57AttributeValueKind.Enumeration),
    CATDAM("CATDAM", null, S57AttributeValueKind.Enumeration),
    CATDIS("CATDIS", null, S57AttributeValueKind.Enumeration),
    CATDOC("CATDOC", null, S57AttributeValueKind.Enumeration),
    CATDPG("CATDPG", null, S57AttributeValueKind.Enumeration),
    CATFIF("CATFIF", null, S57AttributeValueKind.Enumeration),
    CATFOG("CATFOG", null, S57AttributeValueKind.Enumeration),
    CATFOR("CATFOR", null, S57AttributeValueKind.Enumeration),
    CATFRY("CATFRY", null, S57AttributeValueKind.Enumeration),
    CATGAT("CATGAT", null, S57AttributeValueKind.Enumeration),
    CATHAF("CATHAF", null, S57AttributeValueKind.Enumeration),
    CATHLK("CATHLK", null, S57AttributeValueKind.Enumeration),
    CATICE("CATICE", null, S57AttributeValueKind.Enumeration),
    CATINB("CATINB", null, S57AttributeValueKind.Enumeration),
    CATLAM("CATLAM", 37, S57AttributeValueKind.Enumeration),
    CATLIT("CATLIT", null, S57AttributeValueKind.Enumeration),
    CATLMK("CATLMK", null, S57AttributeValueKind.Enumeration),
    CATMFA("CATMFA", null, S57AttributeValueKind.Enumeration),
    CATMPA("CATMPA", null, S57AttributeValueKind.Enumeration),
    CATMOR("CATMOR", null, S57AttributeValueKind.Enumeration),
    CATNAV("CATNAV", null, S57AttributeValueKind.Enumeration),
    CATOBS("CATOBS", 34, S57AttributeValueKind.Enumeration),
    CATOFP("CATOFP", null, S57AttributeValueKind.Enumeration),
    CATOLB("CATOLB", null, S57AttributeValueKind.Enumeration),
    CATPIL("CATPIL", null, S57AttributeValueKind.Enumeration),
    CATPIP("CATPIP", null, S57AttributeValueKind.Enumeration),
    CATPLE("CATPLE", null, S57AttributeValueKind.Enumeration),
    CATPRA("CATPRA", null, S57AttributeValueKind.Enumeration),
    CATPYL("CATPYL", null, S57AttributeValueKind.Enumeration),
    CATQUA("CATQUA", null, S57AttributeValueKind.Enumeration),
    CATRAS("CATRAS", null, S57AttributeValueKind.Enumeration),
    CATREA("CATREA", 56, S57AttributeValueKind.EnumerationList),
    CATRSC("CATRSC", null, S57AttributeValueKind.Enumeration),
    CATRTB("CATRTB", null, S57AttributeValueKind.Enumeration),
    CATTRK("CATTRK", null, S57AttributeValueKind.Enumeration),
    CATTSS("CATTSS", null, S57AttributeValueKind.Enumeration),
    CATVEG("CATVEG", null, S57AttributeValueKind.Enumeration),
    CATWAT("CATWAT", null, S57AttributeValueKind.Enumeration),
    CATWED("CATWED", null, S57AttributeValueKind.Enumeration),
    CATWRK("CATWRK", 71, S57AttributeValueKind.Enumeration),
    COLOUR("COLOUR", 75, S57AttributeValueKind.EnumerationList),
    COLPAT("COLPAT", 76, S57AttributeValueKind.Enumeration),
    COMCHA("COMCHA", null, S57AttributeValueKind.EnumerationList),
    CONDTN("CONDTN", null, S57AttributeValueKind.Enumeration),
    CONRAD("CONRAD", null, S57AttributeValueKind.Decimal),
    CONVIS("CONVIS", null, S57AttributeValueKind.Enumeration),
    DATEND("DATEND", null, S57AttributeValueKind.Text),
    DATSTA("DATSTA", null, S57AttributeValueKind.Text),
    DRVAL1("DRVAL1", 87, S57AttributeValueKind.Decimal),
    DRVAL2("DRVAL2", 88, S57AttributeValueKind.Decimal),
    DUNITS("DUNITS", null, S57AttributeValueKind.Enumeration),
    ELEVAT("ELEVAT", null, S57AttributeValueKind.Decimal),
    ESTRNG("ESTRNG", null, S57AttributeValueKind.Decimal),
    EXCLIT("EXCLIT", null, S57AttributeValueKind.Enumeration),
    EXPSOU("EXPSOU", null, S57AttributeValueKind.Enumeration),
    FUNCTN("FUNCTN", null, S57AttributeValueKind.EnumerationList),
    HEIGHT("HEIGHT", 98, S57AttributeValueKind.Decimal),
    HORACC("HORACC", null, S57AttributeValueKind.Decimal),
    HORCLR("HORCLR", null, S57AttributeValueKind.Decimal),
    HORLEN("HORLEN", null, S57AttributeValueKind.Decimal),
    HORWID("HORWID", null, S57AttributeValueKind.Decimal),
    INFORM("INFORM", 102, S57AttributeValueKind.Text),
    JRSDTN("JRSDTN", null, S57AttributeValueKind.Enumeration),
    LIFCAP("LIFCAP", null, S57AttributeValueKind.Integer),
    LITCHR("LITCHR", 107, S57AttributeValueKind.Enumeration),
    MARSYS("MARSYS", null, S57AttributeValueKind.Enumeration),
    MLTYLT("MLTYLT", null, S57AttributeValueKind.Integer),
    NATION("NATION", null, S57AttributeValueKind.Text),
    NATCON("NATCON", null, S57AttributeValueKind.EnumerationList),
    NOBJNM("NOBJNM", null, S57AttributeValueKind.Text),
    NINFOM("NINFOM", null, S57AttributeValueKind.Text),
    NMDATE("NMDATE", null, S57AttributeValueKind.Text),
    OBJNAM("OBJNAM", 116, S57AttributeValueKind.Text),
    ORIENT("ORIENT", null, S57AttributeValueKind.Decimal),
    PEREND("PEREND", null, S57AttributeValueKind.Text),
    PERSTA("PERSTA", null, S57AttributeValueKind.Text),
    PICREP("PICREP", null, S57AttributeValueKind.Text),
    PILDST("PILDST", null, S57AttributeValueKind.Enumeration),
    PRCTRY("PRCTRY", null, S57AttributeValueKind.Text),
    PRODCT("PRODCT", null, S57AttributeValueKind.EnumerationList),
    PUBREF("PUBREF", null, S57AttributeValueKind.Text),
    QUASOU("QUASOU", null, S57AttributeValueKind.EnumerationList),
    RECDAT("RECDAT", null, S57AttributeValueKind.Text),
    RECIND("RECIND", null, S57AttributeValueKind.Text),
    RESTRN("RESTRN", null, S57AttributeValueKind.EnumerationList),
    RYRMGV("RYRMGV", null, S57AttributeValueKind.Integer),
    SCAMAX("SCAMAX", null, S57AttributeValueKind.Integer),
    SCAMIN("SCAMIN", null, S57AttributeValueKind.Integer),
    SECTR1("SECTR1", null, S57AttributeValueKind.Decimal),
    SECTR2("SECTR2", null, S57AttributeValueKind.Decimal),
    SIGFRQ("SIGFRQ", null, S57AttributeValueKind.Integer),
    SIGGEN("SIGGEN", null, S57AttributeValueKind.Enumeration),
    SIGGRP("SIGGRP", 141, S57AttributeValueKind.Text),
    SIGPER("SIGPER", 142, S57AttributeValueKind.Decimal),
    SIGSEQ("SIGSEQ", null, S57AttributeValueKind.Text),
    SOUACC("SOUACC", null, S57AttributeValueKind.Decimal),
    STATUS("STATUS", null, S57AttributeValueKind.EnumerationList),
    SURATH("SURATH", null, S57AttributeValueKind.Decimal),
    SUREND("SUREND", null, S57AttributeValueKind.Text),
    SURSTA("SURSTA", null, S57AttributeValueKind.Text),
    SURTYP("SURTYP", null, S57AttributeValueKind.Enumeration),
    TECSOU("TECSOU", null, S57AttributeValueKind.EnumerationList),
    TXTDSC("TXTDSC", 156, S57AttributeValueKind.Text),
    TS_TSP("TS_TSP", null, S57AttributeValueKind.Decimal),
    TS_TSV("TS_TSV", null, S57AttributeValueKind.Decimal),
    T_ACWL("T_ACWL", null, S57AttributeValueKind.Decimal),
    VALACM("VALACM", null, S57AttributeValueKind.Decimal),
    VALDCO("VALDCO", 174, S57AttributeValueKind.Decimal),
    VALLMA("VALLMA", null, S57AttributeValueKind.Decimal),
    VALMAG("VALMAG", null, S57AttributeValueKind.Decimal),
    VALMXR("VALMXR", null, S57AttributeValueKind.Decimal),
    VALNMR("VALNMR", null, S57AttributeValueKind.Decimal),
    VALSOU("VALSOU", 179, S57AttributeValueKind.Decimal),
    VERACC("VERACC", null, S57AttributeValueKind.Decimal),
    VERCLR("VERCLR", null, S57AttributeValueKind.Decimal),
    VERCCL("VERCCL", null, S57AttributeValueKind.Decimal),
    VERCSA("VERCSA", null, S57AttributeValueKind.Decimal),
    VERDAT("VERDAT", null, S57AttributeValueKind.Enumeration),
    VERLEN("VERLEN", null, S57AttributeValueKind.Decimal),
    WATLEV("WATLEV", 187, S57AttributeValueKind.Enumeration),

    CATZOC("CATZOC", null, S57AttributeValueKind.Enumeration),
    POSACC("POSACC", null, S57AttributeValueKind.Decimal),
    HORDAT("HORDAT", null, S57AttributeValueKind.Enumeration),
    SORDAT("SORDAT", null, S57AttributeValueKind.Text),
    SORIND("SORIND", null, S57AttributeValueKind.Text);

    companion object {
        private val byAcronym: Map<String, S57Attribute> = entries.associateBy { it.acronym }
        private val byCode: Map<Int, S57Attribute> = entries.mapNotNull { attribute ->
            attribute.code?.let { code -> code to attribute }
        }.toMap()

        fun fromAcronym(value: String): S57Attribute? = byAcronym[value.trim().uppercase()]

        fun fromCode(code: Int): S57Attribute? = byCode[code]

        fun requireAcronym(value: String): S57Attribute =
            fromAcronym(value) ?: error("Unknown S-57 attribute acronym '$value'")
    }
}
